[Tests] add missing link to dynamic-graph
fix:
> /usr/bin/ld: CMakeFiles/testsot-pattern-generator.dir/main.cc.o: undefined reference to symbol '_ZN12dynamicgraph15ExceptionSignalC1ERKNS0_13ErrorCodeEnumERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKcz'